# Generated by Django 4.1.5 on 2023-01-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_work_from_home_resource_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
